from agents.agent.entity.inner.finish import FinishOutput
from agents.agent.entity.inner.wallet_output import WalletOutput


async def sign_with_wallet(unsignedTransaction: str, hitMessage: str = "Please sign the transaction."):
    """
    Sign a transaction with the wallet.
    Args:
        unsignedTransaction (str): The unsigned transaction to be signed.
        hitMessage (str): A friendly prompt automatically generated by the model for signing the transaction based on context. Defaults to "Please sign the transaction."
    Returns:
        str: The signed transaction.
    """
    # return "signed"
    yield WalletOutput({"type": "sign", "unsignedTransaction": unsignedTransaction, "msg": hitMessage})
    yield FinishOutput()
